version: "3.8"
services:
  backend:
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: product-be
    depends_on:
      - db
    environment:
      - DB_HOST=product-db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DRIVER=${DB_DRIVER}
      - LOG_FILE=${LOG_FILE}
      - TOKEN_ISSUE_NAME=${TOKEN_ISSUE_NAME}
      - TOKEN_KEY=${TOKEN_KEY}
      - ACCESS_TOKEN_LIFE_TIME=${ACCESS_TOKEN_LIFE_TIME}
      - REFRESH_TOKEN_LIFE_TIME=${REFRESH_TOKEN_LIFE_TIME}
      - MAILER_HOST=${MAILER_HOST}
      - MAILER_PORT=${MAILER_PORT}
      - MAILER_USERNAME=${MAILER_USERNAME}
      - MAILER_PASSWORD=${MAILER_PASSWORD}
      - MIDTRANS_SERVER_KEY=${MIDTRANS_SERVER_KEY}
    ports:
      - "8081:8080"
    networks:
      - product-network
  db:
    image: postgres:alpine3.17
    container_name: product-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    restart: always
    ports:
      - 5433:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - product-network
volumes:
  db-data:
networks:
  product-network:
